version: "3.9"
services:
    nginx:
        build:
            dockerfile: ./requirements/nginx/Dockerfile
        restart: always
#  wordpress:
#    image: wordpress
#    depends_on:
#        mysql:
#            restart: true
#            condition: service_healthy
#    ports:
#        - 8085:80
#    environment:
#        WORDPRESS_DB_HOST: mysql
#        WORDPRESS_DB_USER: exampleuser
#        WORDPRESS_DB_PASSWORD: examplepass
#        WORDPRESS_DB_NAME: exampledb
#    volumes:
#        - ./requirements/wordpress:/var/www/html
#
#  mysql:
#    image: mysql:8.0
#    restart: always
#    environment:
#        MYSQL_DATABASE: exampledb
#        MYSQL_USER: exampleuser
#        MYSQL_PASSWORD: examplepass
#    volumes:
#        - ./requirements/mariadb:/var/lib/mysql
#    healthcheck:
#        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#        timeout: 20s
#        retries: 10
#
#volumes:
#    wordpress:
#    db:
#services:
#    wordpress:
#        image: wordpress
##        restart: always
#        links:
#        - mariadb:mysql
#        ports:
#        - 8083:80
##        depends_on:
##        - mariadb
#        environment:
##            WORDPRESS_DB_HOST: mariadb
#        - WORDPRESS_DB_USER=root
#        - WORDPRESS_DB_PASSWORD=coffee
##            WORDPRESS_DB_NAME: wpdb
#    mariadb:
#        image: "mariadb:11.2.2"
#        restart: always
#        environment:
#        - MYSQL_DATABASE=wordpress
#        - MYSQL_ROOT_PASSEWORD=coffee
#        volumes:
#        - ./requirements/mariadb:/var/lib/mariadb
#  nginx:
#    image: nginx
#    ports:
#    - "8080:80"
#networks:
#    docker_network:
#        driver: default
