version: "3.8"
services:
    nginx:
        container_name: cnginx
        networks:
        - inception
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        depends_on:
        - wordpress
        env_file: .env
        volumes:
        - wordpress-data:/var/www/wordpress
        ports:
        - 127.0.0.1:443:443
        restart: always
    mariadb:
        container_name: cmaria
        networks:
        - inception # à quel network il appartient
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
        volumes: # Voir plus bas
        - mariadb-data:/var/lib/mysql
        expose:
        - 3306
        restart: always
    wordpress:
        container_name: cwordpress
        networks:
        - inception # à quel network il appartient
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            mariadb:
                restart: true
                condition: service_healthy
        expose:
        - 9000
        volumes:
        - wordpress-data:/var/www/wordpress
volumes:
    wordpress-data:
        driver: local # ici nous stockons le volume en local
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/vboxuser/data/wordpress" #ou stocker en local
    mariadb-data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/vboxuser/data/mariadb"
networks:
    inception:
        driver: bridge
#
#  mysql:
#    image: mysql:8.0
#    restart: always
#    environment:
#        MYSQL_DATABASE: exampledb
#        MYSQL_USER: exampleuser
#        MYSQL_PASSWORD: examplepass
#    volumes:
#        - ./requirements/mariadb:/var/lib/mysql
#    healthcheck:
#        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#        timeout: 20s
#        retries: 10
#
#volumes:
#    wordpress:
#    db:
#services:
#    wordpress:
#        image: wordpress
##        restart: always
#        links:
#        - mariadb:mysql
#        ports:
#        - 8083:80
##        depends_on:
##        - mariadb
#        environment:
##            WORDPRESS_DB_HOST: mariadb
#        - WORDPRESS_DB_USER=root
#        - WORDPRESS_DB_PASSWORD=coffee
##            WORDPRESS_DB_NAME: wpdb
#    mariadb:
#        image: "mariadb:11.2.2"
#        restart: always
#        environment:
#        - MYSQL_DATABASE=wordpress
#        - MYSQL_ROOT_PASSEWORD=coffee
#        volumes:
#        - ./requirements/mariadb:/var/lib/mariadb
#  nginx:
#    image: nginx
#    ports:
#    - "8080:80"
