version: "3.8"
services:
    nginx:
        container_name: cnginx
        networks:
        - netinception # à quel network il appartient
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        env_file: .env
        volumes:
        - wordpress-data:/var/www/html
        depends_on:
        - wordpress
        ports:
        - "443:443"
        restart: unless-stopped

    mariadb:
        container_name: cmaria
        networks:
        - netinception
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
          #        volumes: # Voir plus bas
          #       - mariadb-data:/var/lib/mysql
        expose:
        - "3306"
        restart: unless-stopped
    
    wordpress:
        container_name: cwordpress
        networks:
        - netinception
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
        - mariadb
        expose:
        - "9000"
        restart: unless-stopped
        volumes:
        - wordpress-data:/var/www/html
volumes:
    wordpress-data:
        driver: local # ici nous stockons le volume en local
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/iren/data/wordpress" #ou stocker en local
    mariadb-data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "/home/iren/data/mariadb"
networks:
    netinception:
        driver: bridge
