version: "3.8"
services:
    nginx:
        container_name: cnginx
        networks:
        - inception # à quel network il appartient
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        depends_on:
        - wordpress
        env_file: .env
          #        volumes:
          #        - wordpress-data:/var/www/wordpress
        ports:
        - 127.0.0.1:443:443
        restart: unless-stopped
    mariadb:
        container_name: cmaria
        networks:
        - inception
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
          #        volumes: # Voir plus bas
          #       - mariadb-data:/var/lib/mysql
        expose:
        - 3306
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    wordpress:
        container_name: cwordpress
        networks:
        - inception
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            mariadb:
                condition: service_healthy
                restart: true
        expose:
        - 9000
        restart: unless-stopped
          #        volumes:
          #        - wordpress-data:/var/www/wordpress
          #volumes:
          #    wordpress-data:
          #        driver: local # ici nous stockons le volume en local
          #        driver_opts:
          #            type: "none"
          #            o: "bind"
          #            device: "/home/iren/data/wordpress" #ou stocker en local
          #    mariadb-data:
          #        driver: local
          #        driver_opts:
          #            type: "none"
          #            o: "bind"
          #            device: "/home/iren/data/mariadb"
networks:
    inception:
        driver: bridge
